### ISSUE TITLE
FactoryBot/AssociationStyle false positive with explicit style and `strategy: :build` option

### ISSUE THREAD

**Issue by ydakuka** [rubocop/rubocop-factory_bot#43]
## Actual behavior

I have the factory:

```
FactoryBot.define do
  factory :mask do
    association :blocklist, strategy: :build
  end
end
```

I run the command:

```
ydakuka@yauhenid:~/Work/project$ bin/rails_docker rubocop -A spec/factories/masks.rb
Inspecting 1 file
C

Offenses:

spec/factories/masks.rb:6:5: C: [Corrected] FactoryBot/AssociationStyle: Use implicit style to define associations.
    association :blocklist, strategy: :build
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/factories/masks.rb:6:5: C: [Corrected] FactoryBot/AttributeDefinedStatically: Use a block to declare attribute values.
    blocklist strategy: :build
    ^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 2 offenses detected, 2 offenses corrected
```

Then I got the factory:

```
FactoryBot.define do
  factory :mask do
    blocklist { { strategy: :build } }
  end
end
```

I have the following simple test:

```
context 'when mask is not persisted' do
  let(:mask) { build(:mask) }

  specify do
    mask
  end
end
```

I run the test:
```
ydakuka@yauhenid:~/Work/project$ rspec spec/interactors/masks/create_interactor_spec.rb:171

Masks::CreateInteractor
  when mask is not persisted
    example at ./spec/interactors/masks/create_interactor_spec.rb:171 (FAILED - 1)

Failures:

  1) Masks::CreateInteractor when mask is not persisted 
     Failure/Error: let(:mask) { build(:mask) }
     
     ActiveRecord::AssociationTypeMismatch:
       Blocklist(#86920) expected, got {:strategy=>:build} which is an instance of Hash(#9400)
     # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/associations/association.rb:282:in `raise_on_type_mismatch!'
     # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/associations/belongs_to_association.rb:66:in `replace'
     # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/associations/singular_association.rb:17:in `writer'
     # /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/associations/builder/association.rb:108:in `blocklist='
     # /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/attribute_assigner.rb:16:in `public_send'
     # /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/attribute_assigner.rb:16:in `block (2 levels) in object'
     # /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/attribute_assigner.rb:15:in `each'
     # /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/attribute_assigner.rb:15:in `block in object'
     # /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/attribute_assigner.rb:14:in `tap'
     # /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/attribute_assigner.rb:14:in `object'
     # /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/evaluation.rb:13:in `object'
     # /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/strategy/build.rb:9:in `result'
     # /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/factory.rb:43:in `run'
     # /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/factory_runner.rb:29:in `block in run'
     # /usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/notifications.rb:182:in `instrument'
     # /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/factory_runner.rb:28:in `run'
     # /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/strategy_syntax_method_registrar.rb:28:in `block in define_singular_strategy_method'
     # ./spec/interactors/masks/create_interactor_spec.rb:169:in `block (3 levels) in <top (required)>'
     # ./spec/interactors/masks/create_interactor_spec.rb:172:in `block (3 levels) in <top (required)>'
     # ./spec/support/database_cleaning.rb:18:in `block (3 levels) in <main>'
     # /usr/local/bundle/gems/database_cleaner-core-2.0.1/lib/database_cleaner/strategy.rb:30:in `cleaning'
     # /usr/local/bundle/gems/database_cleaner-core-2.0.1/lib/database_cleaner/cleaners.rb:34:in `block (2 levels) in cleaning'
     # /usr/local/bundle/gems/database_cleaner-core-2.0.1/lib/database_cleaner/strategy.rb:30:in `cleaning'
     # /usr/local/bundle/gems/database_cleaner-core-2.0.1/lib/database_cleaner/cleaners.rb:34:in `block (2 levels) in cleaning'
     # /usr/local/bundle/gems/database_cleaner-core-2.0.1/lib/database_cleaner/cleaners.rb:35:in `cleaning'
     # ./spec/support/database_cleaning.rb:17:in `block (2 levels) in <main>'
     # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <main>'
```

## Debug info

```
ydakuka@yauhenid:~/Work/project$ bin/rails_docker rubocop -d spec/factories/masks.rb
For /app: configuration from /app/.rubocop.yml
configuration from /usr/local/bundle/gems/rubocop-capybara-2.18.0/config/default.yml
Default configuration from /usr/local/bundle/gems/rubocop-1.50.2/config/default.yml
configuration from /usr/local/bundle/gems/rubocop-capybara-2.18.0/lib/../config/default.yml
configuration from /usr/local/bundle/gems/rubocop-factory_bot-2.23.1/config/default.yml
configuration from /usr/local/bundle/gems/rubocop-factory_bot-2.23.1/lib/../config/default.yml
configuration from /usr/local/bundle/gems/rubocop-performance-1.17.1/config/default.yml
configuration from /usr/local/bundle/gems/rubocop-performance-1.17.1/config/default.yml
configuration from /usr/local/bundle/gems/rubocop-rails-2.19.1/config/default.yml
configuration from /usr/local/bundle/gems/rubocop-rails-2.19.1/config/default.yml
configuration from /usr/local/bundle/gems/rubocop-rake-0.6.0/config/default.yml
configuration from /usr/local/bundle/gems/rubocop-rake-0.6.0/config/default.yml
configuration from /usr/local/bundle/gems/rubocop-rspec-2.22.0/config/default.yml
configuration from /usr/local/bundle/gems/rubocop-rspec-2.22.0/config/default.yml
Inheriting configuration from /app/.rubocop_todo.yml
Use parallel by default.
Skipping parallel inspection: only a single file needs inspection
Inspecting 1 file
Scanning /app/spec/factories/masks.rb
Loading cache from /root/.cache/rubocop_cache/3bf2dec38d8afed63f3590777e42f8ba569b3d43/24251ebbddb79bae12a8baba73821326329cc45b/954d37e26309f3ad7ab2ce8f774a1cb935ea93b3
.

1 file inspected, no offenses detected
Finished in 0.5033240660004594 seconds
```

## RuboCop version

```
ydakuka@yauhenid:~/Work/project$ bin/rails_docker rubocop -V
1.50.2 (using Parser 3.2.2.1, rubocop-ast 1.28.1, running on ruby 2.7.8) [x86_64-linux]
  - rubocop-capybara 2.18.0
  - rubocop-performance 1.17.1
  - rubocop-rails 2.19.1
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.22.0
```

## FactoryBot version

```
factory_bot (6.2.1)
  activesupport (>= 5.0.0)
factory_bot_rails (6.2.0)
  factory_bot (~> 6.2.0)
  railties (>= 5.0.0)
```

**Comment by pirj** [comment]
I can reproduce the issue, and I am working on a fix.

Thanks for reporting @ydakuka.

**Comment by pirj** [comment]
Just a note, a few things aren't working intuitively.

1. The `<>` syntax won't accept `(pair :strategy :build)`, only `(pair (sym :strategy) (sym :build))`, while in other cases such a shortcut is possible to my best memory
2. The `<>` rubocop-ast syntax isn't working with `!` negation
3. `!` negation is not documented
4. `foo a: 1` is parsed as `hash` in specs, while `ruby-parse` parses it to `kwargs`

**Comment by pirj** [comment]
Note to self regarding pint 4 above: parser now always returns ‘hash’. This is more practical, as syntactically there’s not much difference. This simplifies cop’s implementation. ‘ruby-parse’ falls back and for some reason turns on all ‘legacy’ settings, and there’s nearly a dozen of them, including the kwargs arguments.
